// Package gencheck compiles the real generated output (component .gen.go +
// registry.gen.go) against runtime to prove the Registry object satisfies
// runtime.SchemaTable structurally. This is a scratch verification package;
// the files in this directory are regenerated by the generator before build.
package gencheck
