// Command spore-gen-go-types renders Spore DSL value-type declarations
// (struct objects) into Go source files.
//
// It now operates in a single-package mode: every .spore file under --in is
// parsed, IDs are resolved globally, and the tool errors out if two files
// declare the same struct name or the same schema ID. This matches the
// sporecode convention of one system namespace per repository.
//
// Output layout for a directory input:
//
//	<out-dir>/agent.gen.go          (from agent._300.spore)
//	<out-dir>/agent.chat.gen.go     (from agent.chat._370.spore)
//	<out-dir>/aigen.gen.go          (from aigen._395.spore)
//	<out-dir>/registry.gen.go       (global ID -> type map)
//	<out-dir>/datatables.gen.go     (--emit-data-tables: @data manifest)
//
// The package name is taken from --package (required). The registry file
// collects every schema ID and type name so runtime dispatchers can resolve
// wire IDs without per-package init() coordination.
//
// Usage:
//
//	spore-gen-go-types \
//	    --in       myxos/schemas \
//	    --out-dir  myxos/pkg/domain/gen \
//	    --package  gen \
//	    --header   "// Code generated by spore-gen-go-types. DO NOT EDIT."
//
// Non-struct objects (classes, interfaces) in the source file are skipped
// silently; spore-gen-go-server is the right tool for callable surfaces.
// Enum declarations are emitted as named Go int types with typed constants.
//
// Parsing goes through the schema-only frontend parser
// (internal/script/frontend), never the script execution runtime: the CLI
// only needs type declarations, so the VM, bytecode, and binding packages
// must not be linked into its dependency graph.
//
// Generation runs through the public gen/render façade — the same entry point
// external embedders use — so the four spore-gen-* CLIs present one symmetric
// public code-generation surface. Only CLI plumbing (flag registration, .spore
// parsing, file IO) comes from internal packages.
package main

import (
	"flag"
	"fmt"
	"io/fs"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"

	"github.com/qomos-w/spore/gen/render"
	"github.com/qomos-w/spore/internal/script/frontend"
	"github.com/qomos-w/spore/schema"
)

const defaultHeader = "// Code generated by spore-gen-go-types. DO NOT EDIT."
const registryFile = "registry.gen.go"
const dataTablesFile = "datatables.gen.go"

func main() {
	var (
		in         = flag.String("in", "", "input .spore file or directory (required)")
		outDir     = flag.String("out-dir", "", "output directory root (required)")
		pkgName    = flag.String("package", "", "Go package name for all emitted files (required)")
		header     = flag.String("header", defaultHeader, "comment header prepended to every generated file")
		noReg      = flag.Bool("no-registry-init", false, "omit spore/schema import and init() registry blocks (dependency-free targets, e.g. the plugin SDK)")
		compVars   = flag.Bool("emit-components", false, "emit runtime.Component[T] descriptor vars for @component structs and the codegen Registry table object consumed by World.AddRegistry (adds a spore/runtime dependency on the per-file descriptor side)")
		dataTables = flag.Bool("emit-data-tables", false, "emit the datatables.gen.go manifest (DataTables + RefShapes) for @data structs: pure stdlib data for consumer-side typed loaders")
		enumImport = flag.String("enum-import", "", "reference enums emitted by another package instead of re-emitting them: `<decl-file>=<go-import-path>`, repeatable; the qualifier is the last path segment (e.g. data/spore/world/enums.spore=github.com/x/barcraft/src/code/model/world)")
		noInitial  = flag.Bool("no-initialisms", false, "export field names in plain PascalCase (pawnId → PawnId, apiUrl → ApiUrl) without ALL_CAPS initialisms, for codebases with pre-existing Go naming")
	)
	flag.Parse()

	if *in == "" || *outDir == "" || *pkgName == "" {
		fmt.Fprintln(os.Stderr, "spore-gen-go-types: --in, --out-dir and --package are required")
		flag.Usage()
		os.Exit(2)
	}

	enumImports, extEnumNames, err := parseEnumImports(*enumImport)
	if err != nil {
		fail(err)
	}

	inputs, err := collectInputs(*in)
	if err != nil {
		fail(err)
	}
	if len(inputs) == 0 {
		fail(fmt.Errorf("no .spore files found under %s", *in))
	}

	// Root for "Source:" labels is the parent of the input so directory runs
	// preserve the relative path (e.g. schemas/agent._300.spore).
	rootForRel := filepath.Dir(filepath.Clean(*in))

	parsed, err := parseAll(inputs, rootForRel, extEnumNames)
	if err != nil {
		fail(err)
	}

	if err := validateGlobalRegistry(parsed); err != nil {
		fail(err)
	}
	if err := validateEnumImports(parsed, enumImports); err != nil {
		fail(err)
	}
	enumNames := collectEnumNames(parsed, extEnumNames)
	if err := render.ValidateGoTypesDataTables(allObjects(parsed), enumNames); err != nil {
		fail(err)
	}

	if err := os.MkdirAll(*outDir, 0o755); err != nil {
		fail(fmt.Errorf("mkdir %s: %w", *outDir, err))
	}

	structNames := collectStructNames(parsed)
	entries := registryEntries(parsed)

	written := 0
	for _, file := range parsed.files {
		outPath := filepath.Join(*outDir, file.stem+".gen.go")
		if err := generateOne(file, outPath, render.GoTypesOptions{
			Package:        *pkgName,
			Header:         *header,
			StructNames:    structNames,
			NoRegistryInit: *noReg,
			EmitComponents: *compVars,
			EnumImports:    enumImports,
			NoInitialisms:  *noInitial,
		}); err != nil {
			fail(fmt.Errorf("%s: %w", file.path, err))
		}
		written++
	}

	writtenRegistry := false
	if len(entries) > 0 {
		registryPath := filepath.Join(*outDir, registryFile)
		reg, err := render.RenderGoTypesRegistry(entries, render.GoTypesOptions{
			Package:        *pkgName,
			Header:         *header,
			NoRegistryInit: *noReg,
			EmitComponents: *compVars,
		})
		if err != nil {
			fail(fmt.Errorf("render registry: %w", err))
		}
		if err := os.WriteFile(registryPath, reg, 0o644); err != nil {
			fail(fmt.Errorf("write %s: %w", registryPath, err))
		}
		writtenRegistry = true
	}

	if *dataTables {
		tables, refs, err := render.BuildGoTypesDataTables(allObjects(parsed), render.GoTypesOptions{EnumImports: enumImports})
		if err != nil {
			fail(err)
		}
		dataPath := filepath.Join(*outDir, dataTablesFile)
		manifest, err := render.RenderGoTypesDataTables(tables, refs, render.GoTypesOptions{
			Package:     *pkgName,
			Header:      *header,
			EnumImports: enumImports,
		})
		if err != nil {
			fail(fmt.Errorf("render data tables: %w", err))
		}
		if err := os.WriteFile(dataPath, manifest, 0o644); err != nil {
			fail(fmt.Errorf("write %s: %w", dataPath, err))
		}
	}

	if writtenRegistry {
		fmt.Fprintf(os.Stderr, "spore-gen-go-types: wrote %d file(s) + %s to %s\n", written, registryFile, *outDir)
	} else {
		fmt.Fprintf(os.Stderr, "spore-gen-go-types: wrote %d file(s) to %s (no schema IDs, registry file skipped)\n", written, *outDir)
	}
}

// parseEnumImports parses the repeatable --enum-import flag
// (`<decl-file>=<go-import-path>`). It returns the render.EnumImport list for
// qualified field rendering and the flat list of external enum names for the
// parse context.
func parseEnumImports(spec string) ([]render.EnumImport, []string, error) {
	if strings.TrimSpace(spec) == "" {
		return nil, nil, nil
	}
	var imports []render.EnumImport
	var names []string
	seenPath := make(map[string]bool)
	seenEnum := make(map[string]string)
	for _, part := range strings.Split(spec, ",") {
		part = strings.TrimSpace(part)
		if part == "" {
			continue
		}
		eq := strings.Index(part, "=")
		if eq <= 0 || eq == len(part)-1 {
			return nil, nil, fmt.Errorf("--enum-import entries must look like <decl-file>=<go-import-path>, got %q", part)
		}
		declFile := strings.TrimSpace(part[:eq])
		importPath := strings.TrimSpace(part[eq+1:])
		if seenPath[importPath] {
			return nil, nil, fmt.Errorf("--enum-import: duplicate import path %q", importPath)
		}
		seenPath[importPath] = true
		src, err := os.ReadFile(declFile)
		if err != nil {
			return nil, nil, fmt.Errorf("--enum-import: read %s: %w", declFile, err)
		}
		enums, err := frontend.ParseAllEnumDescs(string(src))
		if err != nil {
			return nil, nil, fmt.Errorf("--enum-import: parse %s: %w", declFile, err)
		}
		var enumNames []string
		for _, e := range enums {
			if prev, ok := seenEnum[e.Name]; ok {
				return nil, nil, fmt.Errorf("--enum-import: enum %q is declared by both %s and %s", e.Name, prev, declFile)
			}
			seenEnum[e.Name] = declFile
			enumNames = append(enumNames, e.Name)
		}
		imports = append(imports, render.EnumImport{ImportPath: importPath, Enums: enumNames})
		names = append(names, enumNames...)
	}
	return imports, names, nil
}

// validateEnumImports rejects imported enum names that collide with types
// declared in this run: a local struct or enum with the same name would make
// the qualified and unqualified spellings ambiguous.
func validateEnumImports(set *parsedSet, imports []render.EnumImport) error {
	if len(imports) == 0 {
		return nil
	}
	local := make(map[string]bool)
	for _, file := range set.files {
		for _, obj := range file.objs {
			if obj.Kind == schema.TypeKindStruct || obj.Kind == schema.TypeKindClass {
				local[obj.Name] = true
			}
		}
		for _, e := range file.enums {
			local[e.Name] = true
		}
	}
	var errs []string
	for _, imp := range imports {
		for _, name := range imp.Enums {
			if local[name] {
				errs = append(errs, fmt.Sprintf("imported enum %q (from %s) collides with a type declared in --in", name, imp.ImportPath))
			}
		}
	}
	if len(errs) == 0 {
		return nil
	}
	sort.Strings(errs)
	return fmt.Errorf("--enum-import validation failed:\n  - %s", strings.Join(errs, "\n  - "))
}

// collectEnumNames gathers every known enum name (local declarations plus
// --enum-import) for @data key-type validation.
func collectEnumNames(set *parsedSet, extEnumNames []string) map[string]bool {
	names := make(map[string]bool)
	for _, n := range extEnumNames {
		names[n] = true
	}
	for _, file := range set.files {
		for _, e := range file.enums {
			names[e.Name] = true
		}
	}
	return names
}

func allObjects(set *parsedSet) []schema.ObjectDesc {
	var objs []schema.ObjectDesc
	for _, file := range set.files {
		objs = append(objs, file.objs...)
	}
	return objs
}

// parsedFile holds one input file and its struct objects after ID assignment.
type parsedFile struct {
	path        string
	stem        string
	sourceLabel string
	objs        []schema.ObjectDesc
	enums       []schema.EnumDesc
}

// parsedSet holds the full cross-file parse result.
type parsedSet struct {
	files []parsedFile
}

func parseAll(paths []string, rootForRel string, extEnumNames []string) (*parsedSet, error) {
	set := &parsedSet{}

	// Pass 1: collect enum declarations across every file so struct fields in
	// one file can reference enums declared in another (and external enums
	// via --enum-import) and resolve to TypeKindEnum.
	allEnumNames := append([]string(nil), extEnumNames...)
	type fileSrc struct {
		path string
		src  string
	}
	var sources []fileSrc
	for _, p := range paths {
		src, err := os.ReadFile(p)
		if err != nil {
			return nil, fmt.Errorf("read %s: %w", p, err)
		}
		sources = append(sources, fileSrc{path: p, src: string(src)})
		enums, err := frontend.ParseAllEnumDescs(string(src))
		if err != nil {
			return nil, fmt.Errorf("parse enums %s: %w", p, err)
		}
		for _, e := range enums {
			allEnumNames = append(allEnumNames, e.Name)
		}
	}

	// Pass 2: parse object declarations with the full enum name set.
	for _, fs := range sources {
		objs, err := frontend.ParseAllObjectDescsWithEnums(fs.src, allEnumNames)
		if err != nil {
			return nil, fmt.Errorf("parse %s: %w", fs.path, err)
		}
		enums, err := frontend.ParseAllEnumDescs(fs.src)
		if err != nil {
			return nil, fmt.Errorf("parse enums %s: %w", fs.path, err)
		}

		rel, err := filepath.Rel(rootForRel, fs.path)
		if err != nil {
			rel = filepath.Base(fs.path)
		}
		label := filepath.ToSlash(rel)

		// Assign sequential IDs based on filename suffix; explicit @schema(N)
		// annotations are preserved. This is idempotent and per-file.
		render.AssignSequentialSchemaIDs(objs, label)

		stem := deriveStem(fs.path)
		set.files = append(set.files, parsedFile{
			path:        fs.path,
			stem:        stem,
			sourceLabel: label,
			objs:        objs,
			enums:       enums,
		})
	}
	return set, nil
}

func validateGlobalRegistry(set *parsedSet) error {
	type seenEntry struct {
		name string
		file string
	}

	names := make(map[string]seenEntry)
	ids := make(map[uint64]seenEntry)
	var errs []string

	for _, file := range set.files {
		for _, obj := range file.objs {
			if obj.Kind != schema.TypeKindStruct {
				continue
			}
			if obj.IsComponent && obj.SchemaID == 0 {
				errs = append(errs, fmt.Sprintf("@component struct %q (%s) has no schema ID: components are schemas and must declare @schema(N) or live in a file with a numeric base (e.g. agent.chat._300.spore)", obj.Name, file.path))
				continue
			}
			if prev, ok := names[obj.Name]; ok {
				errs = append(errs, fmt.Sprintf("duplicate struct name %q: %s and %s", obj.Name, prev.file, file.path))
			} else {
				names[obj.Name] = seenEntry{name: obj.Name, file: file.path}
			}
			if obj.SchemaID == 0 {
				continue
			}
			if prev, ok := ids[obj.SchemaID]; ok {
				errs = append(errs, fmt.Sprintf("duplicate schema ID %d for structs %q (%s) and %q (%s)", obj.SchemaID, prev.name, prev.file, obj.Name, file.path))
			} else {
				ids[obj.SchemaID] = seenEntry{name: obj.Name, file: file.path}
			}
		}
	}

	// Enums share the package namespace with structs: an enum name colliding
	// with a struct name or another enum breaks the generated package build.
	for _, file := range set.files {
		for _, e := range file.enums {
			if prev, ok := names[e.Name]; ok {
				errs = append(errs, fmt.Sprintf("enum name %q collides with type declared in %s", e.Name, prev.file))
				continue
			}
			names[e.Name] = seenEntry{name: e.Name, file: file.path}
		}
	}

	if len(errs) == 0 {
		return nil
	}
	sort.Strings(errs)
	return fmt.Errorf("schema registry validation failed:\n  - %s", strings.Join(errs, "\n  - "))
}

func collectStructNames(set *parsedSet) map[string]bool {
	names := make(map[string]bool)
	for _, file := range set.files {
		for _, obj := range file.objs {
			if obj.Kind == schema.TypeKindStruct {
				names[obj.Name] = true
			}
		}
	}
	return names
}

func registryEntries(set *parsedSet) []render.RegistryEntry {
	var entries []render.RegistryEntry
	for _, file := range set.files {
		for _, obj := range file.objs {
			if obj.Kind != schema.TypeKindStruct || obj.SchemaID == 0 {
				continue
			}
			entries = append(entries, render.RegistryEntry{
				ID:          obj.SchemaID,
				Name:        obj.Name,
				SourceFile:  file.sourceLabel,
				IsComponent: obj.IsComponent,
			})
		}
	}
	return entries
}

func generateOne(file parsedFile, outPath string, opts render.GoTypesOptions) error {
	opts.SourcePath = file.sourceLabel
	opts.Enums = file.enums
	rendered, err := render.RenderGoTypes(file.objs, opts)
	if err != nil {
		return fmt.Errorf("render: %w", err)
	}

	if err := os.MkdirAll(filepath.Dir(outPath), 0o755); err != nil {
		return fmt.Errorf("mkdir: %w", err)
	}
	if err := os.WriteFile(outPath, rendered, 0o644); err != nil {
		return fmt.Errorf("write %s: %w", outPath, err)
	}
	return nil
}

func collectInputs(path string) ([]string, error) {
	info, err := os.Stat(path)
	if err != nil {
		return nil, fmt.Errorf("stat %s: %w", path, err)
	}
	if !info.IsDir() {
		if filepath.Ext(path) != ".spore" {
			return nil, fmt.Errorf("input %s is not a .spore file", path)
		}
		return []string{path}, nil
	}

	var out []string
	err = filepath.WalkDir(path, func(p string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if d.IsDir() {
			return nil
		}
		if filepath.Ext(p) == ".spore" {
			out = append(out, p)
		}
		return nil
	})
	if err != nil {
		return nil, err
	}
	sort.Strings(out)
	return out, nil
}

// deriveStem maps a source path like "schemas/agent.chat._300.spore" to
// "agent.chat" (the filename with extension and optional _N suffix removed).
// Dots are preserved so generated file names are readable.
func deriveStem(srcPath string) string {
	base := filepath.Base(srcPath)
	base = strings.TrimSuffix(base, ".spore")
	base = stemSuffixRegex.ReplaceAllString(base, "")
	return base
}

var stemSuffixRegex = regexp.MustCompile(`\.\_\d+$`)

func fail(err error) {
	fmt.Fprintln(os.Stderr, "spore-gen-go-types:", err)
	os.Exit(1)
}
